# Generated by Django 5.2.14 on 2026-05-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredient', models.CharField(max_length=50)),
                ('instruction', models.TextField()),
                ('time', models.IntegerField()),
                ('level', models.CharField(max_length=10)),
            ],
        ),
    ]
