# Generated by Django 5.2.14 on 2026-05-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='level',
        ),
    ]
